### ISSUE TITLE
new format

### ISSUE THREAD

**Issue by gstvrmrlpz** [geneura-papers/2015-GPUS#13]
New format added to repo and applied to paper
look for bugs, please

**Comment by gstvrmrlpz** [comment]
new journal is Journal of Parallel and Distributed Computing
http://www.journals.elsevier.com/journal-of-parallel-and-distributed-computing

**Comment by amorag** [comment]
I have revised it, fixed a few typos, changed a bit the title and added a couple of things, such as the acknowledgements (check them, the rest).

The references doesn't have a header, I mean, there is no 'References' section.
Moreover, there are some mistakes is special characters of the bibliography (accents, and so on).
We should check them and change by the Latex code for every one.

**Comment by amorag** [comment]
I have fixed all the special characters in bibliography. ;)

**Comment by amorag** [comment]
I have to adapt it to the new format before the submission. :D
