### ISSUE TITLE
Update all graphics and tables with papers from 2016

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#18]
I just executed the query for year 2016 and I am adding to my database. I'm performing the same analysis, manually setting the type of EA and real problem or not. I will update the results, in the paper in a while. Who generated the graphs, @gstvrmrlpz or @amorag ? Please, create them again, after I update these numbers.

**Comment by fergunet** [comment]
Ok, I've just reviewed new papers, removing all non-related ones and passing from 83 to 29, here are the new data including 2016:

TYPE 
CHAPTER	1
JOURNAL 82
CONFERENCE	111

REAL PROBLEM
YES 126
NO 68

TOTAL
GA 130
GP 38
DE 13
OTHERS 13

Please, @gstvrmrlpz @pacastillo @amorag or whoever created the graphs, update them :)

**Comment by JJ** [comment]
Great job

El martes, 11 de abril de 2017, Pablo García Sánchez <
notifications@github.com> escribió:
> Closed #18 via c2c2337.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/GTMtA-CvWoCtFmwJy_vETVdDf_qoMHAI_W7WrgDl0Sg-ETlzPW9yk2iMdul81iv2tV7DE0sONvL-o6sevS6VMOBpunWZzZeFUT67FK5jd1oe-7OPNoU8bMtVQMGJGoSQTHitHpd73pMu_9H7sK0pGjVvn750bw=s0-d-e1-ft#https://github.com/notifications/beacon/AAAB9G4GXGovlIIr0ZzaWfeJYtPkXRWHks5ru2EpgaJpZM4M3D-p.gif
>

-- 
JJ
