### ISSUE TITLE
Table 2 is too big for the page and overlaps caption and previous paragraph

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GPUS#28]
Please fix it. Maybe use landscape mode.

**Comment by amorag** [comment]
Apparently it's a problem of the compiler.
If you do 'pdflatex' the resulting PDF file shows it properly. ;)

**Comment by JJ** [comment]
That's exactly what I do. You shouldn't close unless you solve the issue.
Acknowledging that it's a real issue and not just somebody being dumb is a
first step.

**Comment by amorag** [comment]
It works for the rest os us, so I didn't consider it an issue.

But anyway, then, I'll assign the issue to the person who designed that table.

**Comment by amorag** [comment]
It works for the rest os us, so I didn't consider it an issue.

But anyway, then, I'll assign the issue to the person who designed that table.
