### ISSUE TITLE
R1: 1. Reduce hardware introduction

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#38]

**Comment by fergunet** [comment]
_The paper takes a lot effort on the hardware introduction, which I think it is away the focus of the paper. Reader can easily get them from any user manuals. The paper should focus on existing researches on parallel EAs rather than hardware comparison and introduction._ 

I think this is debatible.

**Comment by JJ** [comment]
It's not the focus of the paper. Except if you are going to refer to it in the paper, I would slim it down to almost disappearance.

**Comment by gstvrmrlpz** [comment]
The hardware introduction was important in early days of this article but now it is losing relevance with every new release...

**Comment by JJ** [comment]
Exactly. Just summarize it to get the terminology and definitions, and that's that.
