### ISSUE TITLE
R1. 6-7. Minor issues

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#43]
6. “while the GPU processors just run the evaluation stage (as this is usually the computationally hardest task).” This is not true for expensive optimization problems, which are computationally cost tasks but hard to evaluate on GPUs (objective values are obtained by simulations). A condition should be applied here.
7. reference [18] is not complete, the same as [19]?

**Comment by JJ** [comment]
I'll assign it to @pacastillo , who is reviewing bibliography in #35

**Comment by pacastillo** [comment]
I can not completly understand what point-6 means  ???
