### ISSUE TITLE
R2. Papers from 2017

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#47]
Please add papers published in 2017 or later.

**Comment by JJ** [comment]
Also @pacastillo in #35

**Comment by amorag** [comment]
Reviewer 2: 194 selected papers are just roughly classified into 5 categories without summarization

**Comment by pacastillo** [comment]
I have added the following papers (2017 and 2018):

Brito2017
  a classification model for unusual human activities using ensembles of Neural Networks running on NVIDIA GPUs is proposed

Hernandez2017
  we propose to accelerate a bio-inspired model for object classification using CUDA to achieve real-time functionality

Djenouri2017a
  bio-inspired approaches (GA, PSO, and BSO) have been executed on GPU to solve wellknown large ARM instances

Djenouri2017b
  an approach is proposed where the rule evaluation process is parallelized on GPU, while the generation of rules is performed on a multi-core CPU

ZHOU2018
  we present and evaluate a model of vector parallel ACO for multi-core SIMD CPU architecture. In the proposed model, each ant is mapped with a CPU core and the tour construction of each ant is accelerated by vector instructions

Maggiani2018
  we propose a novel heterogeneous architecture for reliable pedestrian detection applications with a neuro-inspired spatio-temporal filter

DJENOURI2018
  This paper investigates the use of GPU (Graphics Processing Unit) in improving the bees swarm optimization metaheuristic performance for solving the association rule mining problem

Rey2018
  a new hybrid approach based on Ant Colony Optimization heuristics, Route First-Cluster Second methods and Local search procedures, combined to generate high quality solutions for the Vehicle Routing Problem

**Comment by pacastillo** [comment]
I will add them as:

ANN + ensembles
  Brito2017,Maggiani2018

bio-inspired
  Hernandez2017,Djenouri2017a,Djenouri2017b,DJENOURI2018

ACO
  ZHOU2018,Rey2018
