### ISSUE TITLE
Decidir a qué revista enviarlo y cambiarle el formato

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#6]

**Comment by amorag** [comment]
Amos a ver.
He rehecho el 'estudio de revistas'. No he encontrado números especiales del tema, así que os pongo los datos de las revistas (ordenados por IF):
- Cluster Computing (CLUSCOMP)
  - IF = 0,94 (Q2)
  - Springer
  - 4 números/año
- Journal of Parallel and Distributed Computing (JPDC)
  - IF = 1,01 (Q2)
  - Elsevier
  - 12 números/año
- International Journal of High Performance Computing Applications (IJHPCA)
  - IF = 1,62 (Q1)
  - Sage
  - 4 números/año
- Parallel Computing (PARCOMP)
  - IF = 1,89 (Q1)
  - Elsevier
  - 12 números/año
- IEEE Transactions on Parallel and Distributed Systems (ToPDS)
  - IF = 2,17 (Q1)
  - IEEE Press
  - 4 números/año

A mi juicio, si le hacemos un buen lavado de cara al artículo deberíamos apuntar a IJHPCA o superior, aunque no conozco la editora y no sé si será chungo publicar en ella.
El inconveniente es que sólo hay 4 números por año, por lo que supongo que tardarán más, aunque seguro que tienen menos envíos que las demás...

Si no, si el artículo queda chulo, podríamos ir a por PARCOMP, que también es Q1 y son 12 números.

Si creéis que el artículo no será muy bueno, entonces a por la JPDC de cabeza. :D

¿Qué opináis?

**Comment by gstvrmrlpz** [comment]
podríamos intentarlo con PARCOMP, que es q1 y como tiene 12 números al año seguramente no tardarán en contestar...

**Comment by amorag** [comment]
Por mi de acuerdo.
Pero entonces hay que dejar el artículo fino y bien desmarcado del de 'los mendas'. ;D

Además el formato es el que tiene actualmente el artículo (el de Elsevier). :P

Así que, si los demás están de acuerdo, cierro el Issue. ;)
