### ISSUE TITLE
Don't use GPGPU instead of GPU

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-GPUS#62]
A GPGPU is just a description of a method that uses a GPU for something other than graphic rendering. It's not a term you should use to describe the actual GPU.

**Comment by pacastillo** [comment]
Do you mean we should change GPGPU to GPU?

**Comment by JJ** [comment]
Only if that's what you mean. Point is, they're different things and the
paper uses Gpgpu when it should use gpu in many cases

**Comment by JJ** [comment]
You can't simply use GPGPU by itself. It refers to something: GPGPU programming, GPGPU framework, GPGPU algorithm.
