### ISSUE TITLE
Discutir el enfoque

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-GPUS#7]
A ver, gente. Si queremos que el artículo prospere hay que darle una vuelta al contenido. @amorag dice que deberíamos quitar las cosas no-evolutivas y centrarlo en evolutivos sólamente, para distinguirlo de otros trabajos parecidos.

Por lo tanto, habría que quitar todas las referencias de ACOs y NN y to eso.

Pregunta: ¿dejamos las secciones como están? (Island, Hybrid...)

**Comment by JJ** [comment]
Podrían ser metaheurísticas en general.

El 8 de junio de 2015, 19:00, Pablo García Sánchez <notifications@github.com

> escribió:
> 
> A ver, gente. Si queremos que el artículo prospere hay que darle una
> vuelta al contenido. @amorag https://github.com/amorag dice que
> deberíamos quitar las cosas no-evolutivas y centrarlo en evolutivos
> sólamente, para distinguirlo de otros trabajos parecidos.
> 
> Por lo tanto, habría que quitar todas las referencias de ACOs y NN y to
> eso.
> 
> Pregunta: ¿dejamos las secciones como están? (Island, Hybrid...)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GPUS/issues/7.

## 

JJ

**Comment by mgarenas** [comment]
Metaheurística es demasiado general no? vamos que ahí podrían entrar 
algoritmos scatter searchs, ACO, Bees, osea más de lo que tenemos ahora, 
no menos no?

Maribel
On 08/06/15 19:01, Juan Julián Merelo Guervós wrote:

> Podrían ser metaheurísticas en general.
> 
> El 8 de junio de 2015, 19:00, Pablo García Sánchez <notifications@github.com
> 
> > escribió:
> > 
> > A ver, gente. Si queremos que el artículo prospere hay que darle una
> > vuelta al contenido. @amorag https://github.com/amorag dice que
> > deberíamos quitar las cosas no-evolutivas y centrarlo en evolutivos
> > sólamente, para distinguirlo de otros trabajos parecidos.
> > 
> > Por lo tanto, habría que quitar todas las referencias de ACOs y NN y to
> > eso.
> > 
> > Pregunta: ¿dejamos las secciones como están? (Island, Hybrid...)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/geneura-papers/2015-GPUS/issues/7.
> 
> ## 
> 
> JJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110073697.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by amorag** [comment]
La cuestión es que ahora mismo el artículo tiene una distribución de metaheurísticas más o menos tal que así (exagerando un poco, claro :D):
- ```
       90% EAs
  ```
- ```
       5% ACOs
  ```
- ```
       3% ANNs
  ```
- ```
       2% Otros
  ```

Si queremos hacerlo más genérico (respecto a todo tipo de metaheurísticas), habría que mejorar mucho lo demás para equilibrar un poco.

Yo voto por hacer lo que sea conveniente para que el artículo se diferencie del de los mendas que se nos adelantaron y creo que el suyo era más genérico y menos exhaustivo. Por eso creo que si nos centramos en EAs, justificándolo bien (son algoritmos ‘fácilmente’ paralelizables, los más paralelizados del mundo mundial, los más usados, nu sé), podríamos ahondar mucho en ellos y desmarcarnos del artículo ese. ;)

¡Taluego!

De: Maribel García Arenas [mailto:notifications@github.com] 
Enviado el: lunes, 8 de junio de 2015 22:35
Para: geneura-papers/2015-GPUS
CC: Antonio Mora
Asunto: Re: [2015-GPUS] Discutir el enfoque (#7)

Metaheurística es demasiado general no? vamos que ahí podrían entrar 
algoritmos scatter searchs, ACO, Bees, osea más de lo que tenemos ahora, 
no menos no?

Maribel
On 08/06/15 19:01, Juan Julián Merelo Guervós wrote:

> Podrían ser metaheurísticas en general.
> 
> El 8 de junio de 2015, 19:00, Pablo García Sánchez <notifications@github.com <mailto:notifications@github.com%0b> 
> 
> > escribió:
> > 
> > A ver, gente. Si queremos que el artículo prospere hay que darle una
> > vuelta al contenido. @amorag https://github.com/amorag dice que
> > deberíamos quitar las cosas no-evolutivas y centrarlo en evolutivos
> > sólamente, para distinguirlo de otros trabajos parecidos.
> > 
> > Por lo tanto, habría que quitar todas las referencias de ACOs y NN y to
> > eso.
> > 
> > Pregunta: ¿dejamos las secciones como están? (Island, Hybrid...)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/geneura-papers/2015-GPUS/issues/7.
> 
> ## 
> 
> JJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110073697.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

—
Reply to this email directly or view it on GitHub https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110129505 .  https://github.com/notifications/beacon/AC6-Wsnkw5nCk4YOsLceQ95p27YA1PEPks5oRfPxgaJpZM4E78sb.gif 

No se encontraron virus en este mensaje.
Comprobado por AVG - www.avg.com
Versión: 2015.0.5961 / Base de datos de virus: 4355/9973 - Fecha de publicación: 06/08/15

**Comment by mgarenas** [comment]
yo apoyo también lo de centrarnos en EAs

Maribel

On 09/06/15 00:59, Antonio Mora wrote:

> La cuestión es que ahora mismo el artículo tiene una distribución de
> metaheurísticas más o menos tal que así (exagerando un poco, claro :D):
> - 90% EAs
> - 5% ACOs
> - 3% ANNs
> - 2% Otros
> 
> Si queremos hacerlo más genérico (respecto a todo tipo de
> metaheurísticas), habría que mejorar mucho lo demás para equilibrar un poco.
> 
> Yo voto por hacer lo que sea conveniente para que el artículo se
> diferencie del de los mendas que se nos adelantaron y creo que el suyo
> era más genérico y menos exhaustivo. Por eso creo que si nos centramos
> en EAs, justificándolo bien (son algoritmos ‘fácilmente’ paralelizables,
> los más paralelizados del mundo mundial, los más usados, nu sé),
> podríamos ahondar mucho en ellos y desmarcarnos del artículo ese. ;)
> 
> ¡Taluego!
> 
> De: Maribel García Arenas [mailto:notifications@github.com]
> Enviado el: lunes, 8 de junio de 2015 22:35
> Para: geneura-papers/2015-GPUS
> CC: Antonio Mora
> Asunto: Re: [2015-GPUS] Discutir el enfoque (#7)
> 
> Metaheurística es demasiado general no? vamos que ahí podrían entrar
> algoritmos scatter searchs, ACO, Bees, osea más de lo que tenemos ahora,
> no menos no?
> 
> Maribel
> On 08/06/15 19:01, Juan Julián Merelo Guervós wrote:
> 
> > Podrían ser metaheurísticas en general.
> > 
> > El 8 de junio de 2015, 19:00, Pablo García Sánchez
> > <notifications@github.com <mailto:notifications@github.com%0b>
> > 
> > > escribió:
> > > 
> > > A ver, gente. Si queremos que el artículo prospere hay que darle una
> > > vuelta al contenido. @amorag https://github.com/amorag dice que
> > > deberíamos quitar las cosas no-evolutivas y centrarlo en evolutivos
> > > sólamente, para distinguirlo de otros trabajos parecidos.
> > > 
> > > Por lo tanto, habría que quitar todas las referencias de ACOs y NN y to
> > > eso.
> > > 
> > > Pregunta: ¿dejamos las secciones como están? (Island, Hybrid...)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/geneura-papers/2015-GPUS/issues/7.
> > 
> > ## 
> > 
> > JJ
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110073697.
> 
> ## 
> 
> "Este mensaje se dirige exclusivamente a su destinatario y puede
> contener información privilegiada o confidencial. Si no es Ud. el
> destinatario indicado, queda notificado de que la utilización,
> divulgación o copia sin autorización está prohibida en virtud de la
> legislación vigente. Si ha recibido este mensaje por error, se ruega lo
> comunique inmediatamente por esta misma vía y proceda a su destrucción.
> 
> This message is intended exclusively for its addressee and may contain
> information that is CONFIDENTIAL and protected by professional
> privilege. If you are not the intended recipient you are hereby notified
> that any dissemination, copy or disclosure of this communication is
> strictly prohibited by law. If this message has been received in error,
> please inmediately notify us via e-mail and delete it"
> 
> María Isabel García Arenas
> Dpto. Arquitectura y Tecnología de los Computadores
> Universidad de Granada
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110129505
> .
> https://github.com/notifications/beacon/AC6-Wsnkw5nCk4YOsLceQ95p27YA1PEPks5oRfPxgaJpZM4E78sb.gif
> 
> No se encontraron virus en este mensaje.
> Comprobado por AVG - www.avg.com
> Versión: 2015.0.5961 / Base de datos de virus: 4355/9973 - Fecha de
> publicación: 06/08/15
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-GPUS/issues/7#issuecomment-110166839.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada

**Comment by gstvrmrlpz** [comment]
me parece bien lo de centrarnos en los EAs

**Comment by JJ** [comment]
ANN no es una metaheurística, aunque es un algoritmo bioinspirado. Pero me parece bien centrarse en los EAs, aunque hay miles.
Podría alguien también revisar los comentarios que llevan ahí en el texto desde hace años...
